### ISSUE TITLE
Error processing requested check "Validation failed"

### ISSUE THREAD

**Issue by diegocl02** [agyemanjp/ci-checks-action#13]
Hi, I'm having this error when running the actions on my report

```
Run agyemanjp/ci-checks-action@2.0.2
[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
checks input: [{"name":"lint","fileName":".lint-report.json","prChangesOnly":true},{"name":"test","fileName":".test-report.json","prChangesOnly":false}]
lint check annotations length: 27
lint check: number of batches = 1
Posting annotations completions for "lint" check
Error: Error processing requested check "lint"
	HttpError: Validation Failed
    at /home/runner/work/_actions/agyemanjp/ci-checks-action/2.0.2/dist/index.js:5887:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error: Error processing requested check "lint"
	HttpError: Validation Failed
    at /home/runner/work/_actions/agyemanjp/ci-checks-action/2.0.2/dist/index.js:5887:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
test check annotations length: 100
test check: number of batches = 2
Processing annotations batch 1 of "test" check
Posting annotations completions for "test" check
```

**Comment by agyemanjp** [comment]
Fixed by #16
